language: python
python:
  - "3.5"
services:
  - docker
env:
  - VERSION=latest
script:
  - docker build -t xianzixiang/node_alpine:$VERSION .
  - echo "$DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xianzixiang/node_alpine:$VERSION
